### ISSUE TITLE
ftp is needed to be updated

### ISSUE THREAD

**Issue by mohseniaref** [dbekaert/TRAIN#3]
Hi David,

I think ftp should be modified in get_ecmwf script to 'ftp://ftp.ceda.ac.uk'
The data path followed this pattern /badc/ecmwf-era-interim/data/gg/ap/ggapYYYYMMDDHHMM.nc

all the best,
MMA

**Comment by dbekaert** [comment]
Hi,

In case you already have this locally could you issue me a pull request for integration?

D.

**Comment by dbekaert** [comment]
Thank you for contributing the pull request
